[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=22.12.0",
]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "hxse", email = "narutohy@163.com"},
]
dependencies = [
    "hid>=1.0.5",
]
requires-python = ">=3.10"
license = {text = "MIT"}
